import type { McpTool, GeneratedFile } from "./types.js";

export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

/** Validate an MCP tool definition before code generation. */
export function validateMcpTool(tool: McpTool): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!tool.name || !tool.name.trim()) {
    errors.push("tool.name is required");
  } else if (!/^[a-zA-Z0-9_-]+$/.test(tool.name)) {
    errors.push(`tool.name '${tool.name}' contains invalid characters (allowed: letters, digits, _ -)`);
  }

  const schema = tool.inputSchema;
  if (!schema) {
    warnings.push("inputSchema is missing — tool takes no typed args");
  } else {
    if (schema.type !== "object") {
      errors.push(`inputSchema.type must be 'object', got '${schema.type}'`);
    }
    const props = schema.properties ?? {};
    for (const req of schema.required ?? []) {
      if (!(req in props)) {
        errors.push(`required field '${req}' is not defined in properties`);
      }
    }
  }

  return { valid: errors.length === 0, errors, warnings };
}

/** Validate a manifest of tools; returns per-tool results. */
export function validateManifest(manifest: { tools?: McpTool[] }): { results: Array<{ name: string; valid: boolean; errors: string[] }>; validCount: number } {
  const results = (manifest.tools ?? []).map((t) => {
    const r = validateMcpTool(t);
    return { name: t.name, valid: r.valid, errors: r.errors };
  });
  return { results, validCount: results.filter((r) => r.valid).length };
}

function tsType(jsonType: string | undefined, hasEnum?: string[]): string {
  if (hasEnum && hasEnum.length) return hasEnum.map(e => `"${e}"`).join(" | ");
  switch (jsonType) {
    case "string": return "string";
    case "number": case "integer": return "number";
    case "boolean": return "boolean";
    case "array": return "unknown[]";
    case "object": return "Record<string, unknown>";
    default: return "unknown";
  }
}

/** Generate typed TypeScript function signatures from MCP tools. */
export function generateTypes(tools: McpTool[], serverName: string): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  let types = `// Auto-generated types for MCP server: ${serverName}\n// Generated by mcp-tool-codegen\n\n`;

  // Generate args interfaces for each tool
  for (const tool of tools) {
    const props = tool.inputSchema?.properties;
    if (!props) continue;
    const pascalName = tool.name.replace(/_([a-z])/g, (_, c) => c.toUpperCase()).replace(/^[a-z]/, s => s.toUpperCase());
    types += `/** ${tool.description || tool.name} */\n`;
    types += `export interface ${pascalName}Args {\n`;
    for (const [key, prop] of Object.entries(props)) {
      if (prop.description) types += `  /** ${prop.description} */\n`;
      const optional = tool.inputSchema?.required?.includes(key) ? "" : "?";
      types += `  ${key}${optional}: ${tsType(prop.type, prop.enum)};\n`;
    }
    types += `}\n\n`;
  }

  // Generate tool function signatures
  let functions = `// Typed tool function signatures for: ${serverName}\n\n`;
  functions += `export interface McpToolResult<T = unknown> {\n  content: Array<{ type: string; text?: string }>;\n  data?: T;\n}\n\n`;

  for (const tool of tools) {
    const props = tool.inputSchema?.properties;
    const pascalName = tool.name.replace(/_([a-z])/g, (_, c) => c.toUpperCase()).replace(/^[a-z]/, s => s.toUpperCase());
    const argsType = props ? `${pascalName}Args` : "Record<string, unknown>";
    functions += `/** ${tool.description || tool.name} */\n`;
    functions += `export type ${pascalName}Fn = (args: ${argsType}) => Promise<McpToolResult>;\n\n`;
  }

  files.push({ path: `${serverName}.types.ts`, content: types });
  files.push({ path: `${serverName}.functions.ts`, content: functions });
  return files;
}
